#!/usr/bin/env python3
"""Generate Stargazing CSS and JSON from the canonical palette specification."""
from __future__ import annotations
import json, math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = json.loads((ROOT / "src/palette.json").read_text())
DIST = ROOT / "dist"
DIST.mkdir(exist_ok=True)
STEPS = ["paper","50","100","150","200","300","400","500","600","700","800","850","900","950","black"]


def srgb_to_linear(x: float) -> float:
    return x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4

def linear_to_srgb(x: float) -> float:
    x = max(0.0, min(1.0, x))
    return 12.92*x if x <= 0.0031308 else 1.055*(x ** (1/2.4))-0.055

def hex_to_oklab(value: str) -> tuple[float,float,float]:
    r,g,b = [srgb_to_linear(int(value[i:i+2],16)/255) for i in (1,3,5)]
    l = 0.4122214708*r + 0.5363325363*g + 0.0514459929*b
    m = 0.2119034982*r + 0.6806995451*g + 0.1073969566*b
    s = 0.0883024619*r + 0.2817188376*g + 0.6299787005*b
    l,m,s = l**(1/3),m**(1/3),s**(1/3)
    return (0.2104542553*l + 0.793617785*m - 0.0040720468*s,
            1.9779984951*l - 2.428592205*m + 0.4505937099*s,
            0.0259040371*l + 0.7827717662*m - 0.8086757660*s)

def oklab_to_hex(lab: tuple[float,float,float]) -> str:
    L,a,b = lab
    l = (L + 0.3963377774*a + 0.2158037573*b)**3
    m = (L - 0.1055613458*a - 0.0638541728*b)**3
    s = (L - 0.0894841775*a - 1.2914855480*b)**3
    rgb = (4.0767416621*l - 3.3077115913*m + 0.2309699292*s,
          -1.2684380046*l + 2.6097574011*m - 0.3413193965*s,
          -0.0041960863*l - 0.7034186147*m + 1.7076147010*s)
    return "#" + "".join(f"{round(linear_to_srgb(x)*255):02X}" for x in rgb)

def hex_to_oklch(value: str) -> dict[str,float]:
    L,a,b = hex_to_oklab(value)
    C = math.hypot(a,b)
    h = (math.degrees(math.atan2(b,a)) + 360) % 360 if C > 1e-10 else 0.0
    return {"l":round(L,6), "c":round(C,6), "h":round(h,3)}

def css_oklch(value: str) -> str:
    c = hex_to_oklch(value)
    return f"oklch({c['l']*100:.4f}% {c['c']:.6f} {c['h']:.3f})"

def ramp(paper: str, ink: str) -> dict[str,str]:
    ref = SPEC["baseReference"]
    ref_lo, ref_hi = hex_to_oklab(ref["black"])[0], hex_to_oklab(ref["paper"])[0]
    positions = {k:(hex_to_oklab(ref[k])[0]-ref_lo)/(ref_hi-ref_lo) for k in STEPS}
    lo, hi = hex_to_oklab(ink), hex_to_oklab(paper)
    return {k:oklab_to_hex(tuple(lo[i]+positions[k]*(hi[i]-lo[i]) for i in range(3))) for k in STEPS}

output = {"name":SPEC["name"], "version":SPEC["version"], "themes":{}, "accents":{}}
for slug, theme in SPEC["themes"].items():
    if "semantic" in theme:
        output["themes"][slug] = {
            "name": theme["name"],
            "method": theme["method"],
            "semantic": {
                mode: {key: {"hex": value, "oklch": hex_to_oklch(value)} for key, value in roles.items()}
                for mode, roles in theme["semantic"].items()
            },
            "terminal": {
                key: {"hex": value, "oklch": hex_to_oklch(value)}
                for key, value in theme["terminal"].items()
            },
        }
    else:
        colors = ramp(theme["paper"], theme["ink"])
        output["themes"][slug] = {"name":theme["name"], "base":{k:{"hex":v,"oklch":hex_to_oklch(v)} for k,v in colors.items()}}
for name, shades in SPEC["accents"].items():
    output["accents"][name] = {k:{"hex":v,"oklch":hex_to_oklch(v)} for k,v in shades.items()}

(DIST / "stargazing.json").write_text(json.dumps(output,indent=2)+"\n")
css = ["/* Generated by scripts/generate.py. Do not edit. */", ":root {"]
for name, shades in SPEC["accents"].items():
    for step, value in shades.items():
        css += [f"  --sg-{name}-{step}: {value};", f"  --sg-{name}-{step}-oklch: {css_oklch(value)};"]
css.append("}\n")
for slug, theme in output["themes"].items():
    css.append(f'[data-stargazing="{slug}"] {{')
    if "base" in theme:
        for step, value in theme["base"].items():
            key = "paper" if step == "paper" else "ink" if step == "black" else f"base-{step}"
            css += [f"  --sg-{key}: {value['hex']};", f"  --sg-{key}-oklch: {css_oklch(value['hex'])};"]
        css += ["", "  /* Light semantic roles */", "  --sg-bg: var(--sg-paper);", "  --sg-bg-2: var(--sg-base-50);", "  --sg-ui: var(--sg-base-100);", "  --sg-ui-2: var(--sg-base-150);", "  --sg-ui-3: var(--sg-base-200);", "  --sg-tx-3: var(--sg-base-300);", "  --sg-tx-2: var(--sg-base-600);", "  --sg-tx: var(--sg-ink);"]
    else:
        css += ["  /* Sparse light semantic roles; aliases are intentional. */"]
        for key, value in theme["semantic"]["light"].items():
            css.append(f"  --sg-{key.replace('Text', '-text').replace('2', '-2').replace('3', '-3')}: {value['hex']};")
    css += ["  --sg-re: var(--sg-red-600); --sg-or: var(--sg-orange-600); --sg-ye: var(--sg-yellow-600); --sg-gr: var(--sg-green-600);", "  --sg-cy: var(--sg-cyan-600); --sg-bl: var(--sg-blue-600); --sg-pu: var(--sg-purple-600); --sg-ma: var(--sg-magenta-600);", "}\n"]
    css.append(f'[data-stargazing="{slug}"][data-mode="dark"], [data-stargazing="{slug}"] [data-mode="dark"] {{')
    if "base" in theme:
        css += ["  --sg-bg: var(--sg-ink);", "  --sg-bg-2: var(--sg-base-950);", "  --sg-ui: var(--sg-base-900);", "  --sg-ui-2: var(--sg-base-850);", "  --sg-ui-3: var(--sg-base-800);", "  --sg-tx-3: var(--sg-base-700);", "  --sg-tx-2: var(--sg-base-500);", "  --sg-tx: var(--sg-base-200);"]
    else:
        for key, value in theme["semantic"]["dark"].items():
            css.append(f"  --sg-{key.replace('Text', '-text').replace('2', '-2').replace('3', '-3')}: {value['hex']};")
    css += ["  --sg-re: var(--sg-red-400); --sg-or: var(--sg-orange-400); --sg-ye: var(--sg-yellow-400); --sg-gr: var(--sg-green-400);", "  --sg-cy: var(--sg-cyan-400); --sg-bl: var(--sg-blue-400); --sg-pu: var(--sg-purple-400); --sg-ma: var(--sg-magenta-400);", "}\n"]
(DIST / "stargazing.css").write_text("\n".join(css))

# Render a deterministic repository preview without browser tooling.
images = ROOT / "_images"
images.mkdir(exist_ok=True)
w, h = 1480, 720
svg = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">',
       f'<rect width="{w}" height="{h}" rx="24" fill="#100F0F"/>',
       '<text x="54" y="72" fill="#F2F0E5" font-family="Georgia,serif" font-size="42">Stargazing</text>',
       '<text x="54" y="105" fill="#878580" font-family="monospace" font-size="13" letter-spacing="2">FOUR PAPERS · ONE PERCEPTUAL SYSTEM</text>']
gap, x0, y0 = 12, 54, 145
col_w = (w - 2*x0 - gap*(len(output["themes"])-1)) // len(output["themes"])
for index, (slug, theme) in enumerate(output["themes"].items()):
    x = x0 + index*(col_w+gap)
    svg.append(f'<text x="{x}" y="{y0}" fill="#CECDC3" font-family="sans-serif" font-size="14">{theme["name"]}</text>')
    if "base" in theme:
        colors = [theme["base"][step]["hex"] for step in STEPS]
    else:
        light = theme["semantic"]["light"]
        dark = theme["semantic"]["dark"]
        colors = [light[key]["hex"] for key in ("bg", "bg2", "ui", "ui2", "ui3", "tx3", "tx2", "tx")] + [dark[key]["hex"] for key in ("tx2", "tx3", "ui3", "ui", "bg2", "bg")]
        colors.insert(8, dark["tx"]["hex"])
    for row, color in enumerate(colors):
        svg.append(f'<rect x="{x}" y="{y0+18+row*22}" width="{col_w}" height="22" fill="{color}"/>')
    svg.append(f'<text x="{x+8}" y="{y0+38}" fill="{colors[-1]}" font-family="monospace" font-size="10">{colors[0]}</text>')
    svg.append(f'<text x="{x+8}" y="{y0+18+15*22-7}" fill="{colors[0]}" font-family="monospace" font-size="10">{colors[-1]}</text>')
accent_y = 526
for row, (name, shades) in enumerate(SPEC["accents"].items()):
    y = accent_y + row*18
    svg.append(f'<text x="54" y="{y+12}" fill="#878580" font-family="monospace" font-size="10">{name[:2].upper()}</text>')
    for col, step in enumerate(shades):
        svg.append(f'<rect x="{86+col*80}" y="{y}" width="76" height="14" rx="3" fill="{shades[step]}"/>')
svg.append('</svg>')
(images / "stargazing-palette.svg").write_text("\n".join(svg)+"\n")
print("Generated CSS, JSON, and palette preview")
